-- FlushPass / WC.exit — shared live terminal state.
-- One table powers both features: the ordered roster of member names AND
-- who currently occupies each toilet. Every browser subscribes to changes.
--
-- Run this once in the Supabase SQL editor.

create table if not exists public.members (
  id        uuid primary key,        -- generated by the browser (localStorage)
  name      text not null,
  stall     text check (stall in ('1','2')),  -- which toilet they hold, or null
  held_at   timestamptz,             -- when the current hold began (for stale-hold cleanup)
  joined_at timestamptz not null default now()
);

-- A toilet can be held by only one member at a time. A conflicting reserve
-- fails at the database, which is our concurrency guard.
create unique index if not exists one_per_stall
  on public.members (stall) where stall is not null;

-- Hackathon-permissive access via the public anon key.
-- (A production build would restrict writes behind auth / an edge function.)
alter table public.members enable row level security;
drop policy if exists "anon all" on public.members;
create policy "anon all" on public.members for all using (true) with check (true);

-- Broadcast row inserts/updates/deletes to all subscribed browsers.
alter publication supabase_realtime add table public.members;
